#!/bin/sh

# before running this script, edit date and version in
# Changelog, PackageInfo.g, etc/VERSION, etc/make_zoo
# etc/changelog.html, doc/manual.tex, doc/installation.tex

(cd ../doc; ./make_doc )

./make_tar

grep -v svg ../README.md > ~/WWW/gap/CaratInterface/README.CaratInterface
cp VERSION                 ~/WWW/gap/CaratInterface
cp changelog.html          ~/WWW/gap/CaratInterface
mv *.tar.gz                ~/WWW/gap/CaratInterface
cp ../PackageInfo.g        ~/WWW/gap/CaratInterface

cd ~/WWW/gap; ./get_html; chmod -R a+r *

