#!/bin/sh

# before running this script, edit date and version in
# Changelog, PackageInfo.g, etc/VERSION, etc/make_zoo
# etc/changelog.html, doc/manual.tex, doc/installation.tex

(cd ../doc; ./make_doc )

./make_tar

cp ../README        ~/WWW/gap/Carat/README.carat
cp VERSION          ~/WWW/gap/Carat
cp changelog.html   ~/WWW/gap/Carat
mv *.tar.gz         ~/WWW/gap/Carat
cp ../PackageInfo.g ~/WWW/gap/Carat

cd ~/WWW/gap; ./get_html; chmod -R a+r *

