#!/bin/sh

# before running this script, edit date and version in
# Changelog, PackageInfo.g, etc/VERSION, etc/make_zoo
# etc/changelog.html, doc/manual.tex, doc/installation.tex

(cd ../doc; ./make_doc )

./make_tar

cp ../README        ~/WWW/gap45/Carat/README.carat
cp VERSION          ~/WWW/gap45/Carat
cp changelog.html   ~/WWW/gap45/Carat
mv *.tar.gz         ~/WWW/gap45/Carat
cp ../PackageInfo.g ~/WWW/gap45/Carat

cd ~/WWW/gap45; ./get_html; chmod -R a+r *

