#!/bin/sh

PKGZOO=carat-1.1.zoo
DOCZOO=carat-doc-1.1.zoo

# remove old archives
rm -f $PKGZOO
rm -f $DOCZOO

# goto <gaproot>/pkg
cd ../..

# make the package archive

# first the binary files
echo "!BINARY!" | zoo ach carat/etc/$PKGZOO carat/doc/manual.dvi
echo "!BINARY!" | zoo ach carat/etc/$PKGZOO carat/doc/manual.pdf
echo "!BINARY!" | zoo ach carat/etc/$PKGZOO carat/carat-1.2.tar.gz

# then the text files
echo "!TEXT!" | zoo ach carat/etc/$PKGZOO carat/doc/manual.tex
echo "!TEXT!" | zoo ach carat/etc/$PKGZOO carat/doc/manual.bbl
echo "!TEXT!" | zoo ach carat/etc/$PKGZOO carat/doc/manual.six
echo "!TEXT!" | zoo ach carat/etc/$PKGZOO carat/doc/manual.lab
echo "!TEXT!" | zoo ach carat/etc/$PKGZOO carat/doc/manual.mst
echo "!TEXT!" | zoo ach carat/etc/$PKGZOO carat/doc/manual.ps
echo "!TEXT!" | zoo ach carat/etc/$PKGZOO carat/doc/carat.tex
echo "!TEXT!" | zoo ach carat/etc/$PKGZOO carat/doc/introduction.tex
echo "!TEXT!" | zoo ach carat/etc/$PKGZOO carat/doc/installation.tex
echo "!TEXT!" | zoo ach carat/etc/$PKGZOO carat/doc/make_doc
echo "!TEXT!" | zoo ach carat/etc/$PKGZOO carat/init.g
echo "!TEXT!" | zoo ach carat/etc/$PKGZOO carat/read.g
echo "!TEXT!" | zoo ach carat/etc/$PKGZOO carat/README
echo "!TEXT!" | zoo ach carat/etc/$PKGZOO carat/Changelog
for file in carat/gap/*.g[di] ; do
  echo "!TEXT!" | zoo ach carat/etc/$PKGZOO $file
done
for file in carat/htm/*.htm ; do
  echo "!TEXT!" | zoo ach carat/etc/$PKGZOO $file
done

# make the package documentation archive

echo "!BINARY!" | zoo ach carat/etc/$DOCZOO carat/doc/manual.pdf
echo "!TEXT!"   | zoo ach carat/etc/$DOCZOO carat/doc/manual.six
for file in carat/htm/*.htm ; do
  echo "!TEXT!" | zoo ach carat/etc/$DOCZOO $file
done

# check the results

cd carat/etc
zoo -list $PKGZOO
zoo -list $DOCZOO

