#!/bin/sh

PKGTAR=carat-2.3.1.tar

# remove old archive
rm -f $PKGTAR*

# update documentaion
(cd ../doc; ./make_doc;)

# make the package archive
mkdir -p carat/doc carat/gap carat/htm carat/tst
cd carat
  git clone https://github.com/lbfm-rwth/carat.git
  (cd carat && ./autogen.sh)
  tar zcf carat.tgz --exclude=carat/.git carat 
  rm -rf carat
cd ..
cp -p ../*.g ../README ../INSTALL ../Changelog ../GPL carat/
cp -p ../Makefile ../configure carat/
cp -p ../doc/manual.bbl ../doc/manual.six ../doc/manual.lab ../doc/manual.toc \
  ../doc/manual.mst ../doc/manual.pdf ../doc/*.tex ../doc/make_doc carat/doc/
cp -p ../gap/*.g[di] carat/gap/
cp -p ../htm/*.htm carat/htm/
cp -p ../tst/*.g ../tst/*.tst  carat/tst/
chmod -R a+rX carat 
tar cvf $PKGTAR carat
chmod a+r $PKGTAR
gzip $PKGTAR

# cleanup
rm -rf carat
