#!/bin/sh

PKGTAR=carat-2.1.3.tar

# remove old archive
rm -f $PKGTAR*

# update documentaion
(cd ../doc; ./make_doc; chmod a+r *; cd ../htm; chmod a+r *)

# goto <gaproot>/pkg
cd ../..

# make the package archive
tar cvf carat/etc/$PKGTAR carat/doc/manual.* carat/doc/*.tex \
  carat/doc/make_doc carat/*.g carat/README carat/Changelog carat/GPL \
  carat/gap/*.g[di] carat/htm/*.htm carat/carat-2.1b1.tgz

# compress the result
cd carat/etc
chmod a+r $PGKTAR
gzip $PKGTAR
