#!/bin/sh

# remove old archive
rm -f carat.zoo

# goto <gaproot>/pkg
cd ../..

# first the binary files
echo "\!BINARY\!\n/END" | zoo ach carat/etc/carat.zoo carat/doc/manual.dvi
echo "\!BINARY\!\n/END" | zoo ach carat/etc/carat.zoo carat/carat.1.1b.tar.gz

# then the text files
echo "\!TEXT\!\n/END" | zoo ach carat/etc/carat.zoo carat/doc/manual.tex
echo "\!TEXT\!\n/END" | zoo ach carat/etc/carat.zoo carat/doc/manual.bbl
echo "\!TEXT\!\n/END" | zoo ach carat/etc/carat.zoo carat/doc/manual.six
echo "\!TEXT\!\n/END" | zoo ach carat/etc/carat.zoo carat/doc/manual.mst
echo "\!TEXT\!\n/END" | zoo ach carat/etc/carat.zoo carat/doc/manual.ps
echo "\!TEXT\!\n/END" | zoo ach carat/etc/carat.zoo carat/doc/carat.tex
echo "\!TEXT\!\n/END" | zoo ach carat/etc/carat.zoo carat/doc/preface.tex
echo "\!TEXT\!\n/END" | zoo ach carat/etc/carat.zoo carat/doc/make_doc
echo "\!TEXT\!\n/END" | zoo ach carat/etc/carat.zoo carat/init.g
echo "\!TEXT\!\n/END" | zoo ach carat/etc/carat.zoo carat/read.g
echo "\!TEXT\!\n/END" | zoo ach carat/etc/carat.zoo carat/README
echo "\!TEXT\!\n/END" | zoo ach carat/etc/carat.zoo carat/Changelog
for file in carat/gap/*.g[di] ; do
  echo "\!TEXT\!\n/END" | zoo ach carat/etc/carat.zoo $file
done
for file in carat/htm/*.htm ; do
  echo "\!TEXT\!\n/END" | zoo ach carat/etc/carat.zoo $file
done

# the empty bin directory
# zoo ah carat/etc/carat.zoo carat/bin

# check result
cd carat/etc
zoo -list carat.zoo

